# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-11 08:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=400, null=True, verbose_name='标题')),
                ('info', models.TextField(blank=True, null=True, verbose_name='问题说明')),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='发布时间')),
                ('publisher', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='publisher', to='QA.UserProfile', verbose_name='发布人')),
            ],
        ),
    ]
