# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-14 08:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0004_auto_20170511_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='QA/static/images/ironmen.png', upload_to='avatar_image', verbose_name='头像'),
        ),
    ]
