# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-14 09:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0005_auto_20170514_1655'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='avatar',
            field=models.ImageField(default='avatar_image/ironmen.png', upload_to='avatar_image', verbose_name='头像'),
        ),
    ]
