# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-15 07:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0006_auto_20170514_1701'),
    ]

    operations = [
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vote_count', models.IntegerField(blank=True, null=True, verbose_name='赞同数')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now, verbose_name='发布时间')),
                ('content', models.TextField(blank=True, null=True, verbose_name='回答内容')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='pv_count',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='question',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='QA.UserProfile', verbose_name='发布问题的人'),
        ),
        migrations.AddField(
            model_name='answer',
            name='belong_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='QA.Question', verbose_name='所关联的问题'),
        ),
        migrations.AddField(
            model_name='answer',
            name='publisher',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='QA.UserProfile', verbose_name='撰写回答的人'),
        ),
    ]
