# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-15 07:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0007_auto_20170515_1530'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='publisher',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='answers', to='QA.UserProfile', verbose_name='撰写回答的人'),
        ),
    ]
