# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-15 09:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0008_auto_20170515_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='频道')),
            ],
        ),
        migrations.AddField(
            model_name='question',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='QA.Channel', verbose_name='频道'),
        ),
    ]
