# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-15 11:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0009_auto_20170515_1713'),
    ]

    operations = [
        migrations.AlterField(
            model_name='channel',
            name='name',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True, verbose_name='频道'),
        ),
    ]
