# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-23 01:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0012_auto_20170523_0925'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='question',
            name='tag',
        ),
    ]
