# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2017-05-29 07:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('QA', '0013_remove_question_tag'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.CharField(blank=True, max_length=500, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('belong_to_userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='QA.UserProfile')),
                ('reply_to', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='QA.Comment')),
            ],
        ),
        migrations.CreateModel(
            name='Ticket',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('choose', models.CharField(blank=True, choices=[('like', 'like'), ('unlike', 'unlike')], max_length=10, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('belong_to_answer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='QA.Answer')),
                ('belong_to_userprofile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tickets', to='QA.UserProfile')),
            ],
        ),
    ]
